/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.dsl.ide;

import org.xtext.example.dsl.ide.AbstractDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DslIdeModule extends AbstractDslIdeModule {
}
