/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.dsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.dsl.DslRuntimeModule
import org.xtext.example.dsl.DslStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DslIdeSetup extends DslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DslRuntimeModule, new DslIdeModule))
	}
	
}
